# Generated by Django 4.1.4 on 2022-12-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
